In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

In [2]:
np.__version__

'1.21.2'

In [3]:
pd.__version__

'1.3.2'

In [4]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

#### Average price, BMW assuming MSRP is prirce

In [5]:
df[df['Make'] == 'BMW']['MSRP'].mean()

61546.76347305389

#### Number of cars afrer 2015

In [46]:
df_after_2015 = df[df['Year'] >= 2015]

#### Number of Enginer HP which are null

In [47]:
df_after_2015[df_after_2015['Engine HP'].isna()].shape

(51, 16)

#### Mean before fillna

In [48]:
mean_hp_before = df['Engine HP'].mean()

In [49]:
mean_hp_before

249.38607007176023

In [50]:
mean_hp_after = df['Engine HP'].fillna(mean_hp_before).mean()

In [51]:
df['Engine HP'].fillna(mean_hp_before)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [52]:
mean_hp_after

249.38607007176023

In [53]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


#### Rolls-Royce

In [13]:
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [14]:
rolls_royce = df[df['Make'] == 'Rolls-Royce']

In [15]:
rolls_royce = rolls_royce[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [16]:
rolls_royce.head()

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19
5275      563.0              12.0           21
5276      563.0              12.0           21
5277      563.0              12.0           21

In [17]:
non_duplicate_rr = rolls_royce.drop_duplicates()

In [18]:
non_duplicate_rr.shape

(7, 3)

In [19]:
X = non_duplicate_rr.to_numpy()

In [55]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [57]:
X.T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [91]:
XTX = X.T.dot(X)

In [92]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [93]:
from numpy.linalg import inv

In [94]:
iXTX = inv(XTX.astype(int))

In [95]:
iXTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [96]:
iXTX.sum()

0.032212320677486125

#### Question 7

In [97]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [102]:
w = (iXTX.dot(X.T)).dot()

In [103]:
w

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])